import { z } from 'zod';

/** All 17 QAForge pipeline agents */
export const AgentId = {
  REQUIREMENT_ANALYSIS: 'REQUIREMENT_ANALYSIS',
  REQUIREMENT_CLARIFICATION: 'REQUIREMENT_CLARIFICATION',
  AUTHENTICATION: 'AUTHENTICATION',
  APPLICATION_DISCOVERY: 'APPLICATION_DISCOVERY',
  FUNCTIONAL_TESTING: 'FUNCTIONAL_TESTING',
  UI_UX_REVIEW: 'UI_UX_REVIEW',
  API_TESTING: 'API_TESTING',
  ACCESSIBILITY: 'ACCESSIBILITY',
  PERFORMANCE: 'PERFORMANCE',
  SECURITY_REVIEW: 'SECURITY_REVIEW',
  PRODUCT_IMPROVEMENT: 'PRODUCT_IMPROVEMENT',
  TEST_CASE_GENERATION: 'TEST_CASE_GENERATION',
  AUTOMATION_GENERATION: 'AUTOMATION_GENERATION',
  EXECUTION: 'EXECUTION',
  FAILURE_ANALYSIS: 'FAILURE_ANALYSIS',
  REPORT_GENERATION: 'REPORT_GENERATION',
  GITHUB_INTEGRATION: 'GITHUB_INTEGRATION',
  GITHUB_ACTIONS: 'GITHUB_ACTIONS',
} as const;

export type AgentId = (typeof AgentId)[keyof typeof AgentId];

export const agentIdSchema = z.enum([
  'REQUIREMENT_ANALYSIS',
  'REQUIREMENT_CLARIFICATION',
  'AUTHENTICATION',
  'APPLICATION_DISCOVERY',
  'FUNCTIONAL_TESTING',
  'UI_UX_REVIEW',
  'API_TESTING',
  'ACCESSIBILITY',
  'PERFORMANCE',
  'SECURITY_REVIEW',
  'PRODUCT_IMPROVEMENT',
  'TEST_CASE_GENERATION',
  'AUTOMATION_GENERATION',
  'EXECUTION',
  'FAILURE_ANALYSIS',
  'REPORT_GENERATION',
  'GITHUB_INTEGRATION',
  'GITHUB_ACTIONS',
]);
