import type { ActionEntry } from '@qaforge/shared';

/**
 * Replay a recorded ActionLog against a Playwright page (0 LLM).
 * Locators are evaluated as expressions on `page`.
 */
export async function replayActionLog(
  page: import('playwright').Page,
  actions: ActionEntry[],
  env: {
    appUrl: string;
    loginUrl?: string | null;
    username?: string;
    password?: string;
    firstName?: string;
    lastName?: string;
    postalCode?: string;
  },
): Promise<void> {
  const envMap: Record<string, string> = {
    APP_URL: env.appUrl,
    LOGIN_URL: env.loginUrl || env.appUrl,
    APP_USER: env.username || '',
    APP_PASS: env.password || '',
    FIRST_NAME: env.firstName || 'Jane',
    LAST_NAME: env.lastName || 'Doe',
    POSTAL_CODE: env.postalCode || '12345',
  };

  for (const a of actions) {
    const timeout = a.timeoutMs ?? 15_000;
    switch (a.kind) {
      case 'goto': {
        const url =
          (a.urlEnv ? envMap[a.urlEnv] : undefined) ||
          a.urlLiteral ||
          env.appUrl;
        await page.goto(url, {
          waitUntil: 'domcontentloaded',
          timeout,
        });
        break;
      }
      case 'click': {
        if (!a.locator) break;
        const loc = evalLocator(page, a.locator);
        await loc.click({ timeout });
        break;
      }
      case 'fill': {
        if (!a.locator) break;
        const value = a.valueEnv
          ? envMap[a.valueEnv] || a.valueLiteral || ''
          : (a.valueLiteral ?? '');
        const loc = evalLocator(page, a.locator);
        await loc.fill(value, { timeout });
        break;
      }
      case 'select': {
        if (!a.locator) break;
        const loc = evalLocator(page, a.locator);
        if (a.selectValue) {
          await loc.selectOption({ value: a.selectValue }, { timeout });
        } else if (a.selectLabel) {
          await loc.selectOption({ label: a.selectLabel }, { timeout });
        }
        break;
      }
      case 'waitFor': {
        if (!a.locator) break;
        const loc = evalLocator(page, a.locator);
        await loc.waitFor({
          state: a.waitState ?? 'visible',
          timeout,
        });
        break;
      }
      case 'wait': {
        await page.waitForTimeout(a.timeoutMs ?? 400);
        break;
      }
      default:
        break;
    }
  }
}

function evalLocator(
  page: import('playwright').Page,
  expr: string,
): import('playwright').Locator {
  // Expressions are generated by our recorder (trusted). Evaluate as page.<expr>
  // eslint-disable-next-line no-new-func
  const fn = new Function(
    'page',
    `return page.${expr};`,
  ) as (p: import('playwright').Page) => import('playwright').Locator;
  return fn(page);
}

export function parseActionLog(raw: unknown): ActionEntry[] {
  if (!Array.isArray(raw)) return [];
  return raw.filter(
    (a): a is ActionEntry =>
      Boolean(a) &&
      typeof a === 'object' &&
      typeof (a as ActionEntry).kind === 'string',
  );
}
