import type { AgentHandler } from '@qaforge/agent-sdk';
import { ArtifactType } from '@qaforge/shared';
import { putBinaryArtifact } from '../context.js';

type AutomationInput = {
  projectName: string;
  appUrl: string;
  framework: string;
  language: string;
};

function buildFrameworkFiles(input: AutomationInput): Record<string, string> {
  const pkgName = input.projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'qaforge-tests';

  return {
    'package.json': JSON.stringify(
      {
        name: `${pkgName}-automation`,
        version: '1.0.0',
        private: true,
        scripts: {
          test: 'playwright test',
          'test:headed': 'playwright test --headed',
          report: 'playwright show-report',
        },
        devDependencies: {
          '@playwright/test': '^1.51.0',
          typescript: '^5.8.2',
          '@types/node': '^22.13.10',
        },
      },
      null,
      2,
    ),
    'playwright.config.ts': `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './src/tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: [['list'], ['html', { open: 'never' }], ['junit', { outputFile: 'results/junit.xml' }]],
  use: {
    baseURL: process.env.BASE_URL || '${input.appUrl}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
`,
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'commonjs',
          moduleResolution: 'node',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          types: ['node'],
          outDir: 'dist',
          rootDir: 'src',
        },
        include: ['src/**/*', 'playwright.config.ts'],
      },
      null,
      2,
    ),
    'README.md': `# ${input.projectName} — Playwright Automation

Generated by **QAForge AI**.

## Setup

\`\`\`bash
npm install
npx playwright install chromium
cp .env.example .env
\`\`\`

## Run

\`\`\`bash
npm test
\`\`\`

Base URL defaults to \`${input.appUrl}\`.
`,
    '.gitignore': `node_modules/
test-results/
playwright-report/
results/
dist/
.env
.DS_Store
`,
    Dockerfile: `FROM mcr.microsoft.com/playwright:v1.51.0-jammy
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci || npm install
COPY . .
CMD ["npx", "playwright", "test"]
`,
    '.env.example': `BASE_URL=${input.appUrl}
# Never commit real credentials. Prefer interactive or secret-store auth.
`,
    '.github/workflows/qaforge.yml': `name: QAForge Playwright

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - run: npm ci || npm install
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test
        env:
          BASE_URL: \${{ vars.BASE_URL || '${input.appUrl}' }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            results/
            test-results/
`,
    'src/pages/BasePage.ts': `import type { Page, Locator } from '@playwright/test';
import { logger } from '../utils/logger';

export abstract class BasePage {
  constructor(protected readonly page: Page) {}

  async goto(path = '/'): Promise<void> {
    logger.info(\`Navigate \${path}\`);
    await this.page.goto(path, { waitUntil: 'domcontentloaded' });
  }

  async click(locator: Locator): Promise<void> {
    await locator.waitFor({ state: 'visible' });
    await locator.click();
  }

  async fill(locator: Locator, value: string): Promise<void> {
    await locator.waitFor({ state: 'visible' });
    await locator.fill(value);
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
`,
    'src/pages/LoginPage.ts': `import type { Page } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * Login Page Object — does not hardcode credentials.
 * Credentials should come from env/secret store at runtime.
 */
export class LoginPage extends BasePage {
  readonly email = this.page.locator(
    'input[type="email"], input[name*="email" i], input[id*="email" i]',
  ).first();
  readonly password = this.page.locator('input[type="password"]').first();
  readonly submit = this.page.locator(
    'button[type="submit"], input[type="submit"], button:has-text("Log in"), button:has-text("Sign in")',
  ).first();

  constructor(page: Page) {
    super(page);
  }

  async open(loginPath = '/login'): Promise<void> {
    await this.goto(loginPath);
  }

  async login(email: string, password: string): Promise<void> {
    await this.fill(this.email, email);
    await this.fill(this.password, password);
    await this.click(this.submit);
  }
}
`,
    'src/pages/HomePage.ts': `import type { Page } from '@playwright/test';
import { BasePage } from './BasePage';

export class HomePage extends BasePage {
  readonly nav = this.page.locator('nav, [role="navigation"]').first();
  readonly heading = this.page.locator('h1, [data-testid="page-title"]').first();

  constructor(page: Page) {
    super(page);
  }

  async expectLoaded(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
  }
}
`,
    'src/tests/smoke.spec.ts': `import { test, expect } from '@playwright/test';
import { HomePage } from '../pages/HomePage';
import { testData } from '../fixtures/test-data';

test.describe('Smoke', () => {
  test('home loads', async ({ page }) => {
    const home = new HomePage(page);
    await home.goto('/');
    await home.expectLoaded();
    await expect(page).toHaveURL(new RegExp(testData.urlPattern));
    const title = await home.getTitle();
    expect(title.length).toBeGreaterThan(0);
  });
});
`,
    'src/fixtures/test-data.ts': `export const testData = {
  baseUrl: process.env.BASE_URL || '${input.appUrl}',
  urlPattern: '.*',
};
`,
    'src/utils/logger.ts': `export const logger = {
  info(message: string, meta?: unknown): void {
    console.log(JSON.stringify({ level: 'info', message, meta, ts: new Date().toISOString() }));
  },
  error(message: string, meta?: unknown): void {
    console.error(JSON.stringify({ level: 'error', message, meta, ts: new Date().toISOString() }));
  },
};
`,
  };
}

export const automationAgent: AgentHandler<AutomationInput, unknown> = {
  id: 'AUTOMATION_GENERATION',
  name: 'Automation Agent',

  async run(ctx, input) {
    const files = buildFrameworkFiles(input);
    const fileList = Object.keys(files);

    for (const [rel, content] of Object.entries(files)) {
      await putBinaryArtifact({
        executionId: ctx.executionId,
        type: ArtifactType.AUTOMATION_FRAMEWORK,
        key: `${ctx.executionId}/framework/${rel}`,
        body: content,
        mime: rel.endsWith('.json')
          ? 'application/json'
          : rel.endsWith('.md')
            ? 'text/markdown'
            : 'text/plain',
        store: ctx.artifactStore,
      });
    }

    const manifest = {
      framework: input.framework || 'PLAYWRIGHT',
      language: input.language || 'TYPESCRIPT',
      files: fileList,
      baseUrl: input.appUrl,
      generatedAt: new Date().toISOString(),
    };

    await ctx.putArtifactJson('AUTOMATION_MANIFEST', manifest);
    await ctx.emit({
      type: 'automation.ready',
      phase: 'AUTOMATION',
      message: `Playwright POM framework generated (${fileList.length} files)`,
      data: { fileCount: fileList.length },
    });

    return { files, manifest };
  },
};
