'use client';

import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import { getDefaultOrgId } from '@/lib/org';
import { Badge } from '@/components/Badge';
import { Button } from '@/components/Button';
import {
  ListingEmpty,
  ListingPager,
  ListingTable,
  listingFilterClass,
  listingSearchClass,
  useListingSlice,
} from '@/components/ListingTable';
import { TcmsAiExecutorModal } from './tcms-ai-executor-modal';
import { resultTone, runHref } from './tcms-types';

export type AutomatedScriptRow = {
  id: string;
  testCaseId: string;
  path: string;
  lastRunId?: string | null;
  lastStatus?: string | null;
  updatedAt: string;
  externalId: string;
  scenario: string;
  priorityLabel: string;
  folderName?: string | null;
};

const RESULT_FILTERS = ['PASSED', 'FAILED', 'RUNNING'] as const;
const PRIORITY_FILTERS = ['HIGH', 'MEDIUM', 'LOW'] as const;

export function TcmsAutomationPanel({
  projectId,
  canEdit,
  onRun,
}: {
  projectId: string;
  canEdit: boolean;
  onRun?: () => void;
}) {
  const router = useRouter();
  const qc = useQueryClient();
  const [search, setSearch] = useState('');
  const [resultFilter, setResultFilter] = useState('');
  const [priorityFilter, setPriorityFilter] = useState('');
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [executorOpen, setExecutorOpen] = useState(false);
  const [executorIds, setExecutorIds] = useState<string[] | undefined>();
  const [error, setError] = useState<string | null>(null);

  const scriptsQuery = useQuery({
    queryKey: ['tcms-automation-scripts', projectId],
    queryFn: async () => {
      const orgId = await getDefaultOrgId();
      return api<AutomatedScriptRow[]>(
        `/api/v1/orgs/${orgId}/projects/${projectId}/tcms/automation/scripts`,
      );
    },
    refetchInterval: 8000,
  });

  const envQuery = useQuery({
    queryKey: ['project', projectId],
    queryFn: async () => {
      const orgId = await getDefaultOrgId();
      return api<{ appUrl?: string | null }>(
        `/api/v1/orgs/${orgId}/projects/${projectId}`,
      );
    },
  });

  const scripts = scriptsQuery.data ?? [];
  const filtered = useMemo(() => {
    let rows = scripts;
    if (resultFilter) {
      rows = rows.filter((r) => r.lastStatus === resultFilter);
    }
    if (priorityFilter) {
      rows = rows.filter((r) => r.priorityLabel === priorityFilter);
    }
    return rows;
  }, [scripts, resultFilter, priorityFilter]);
  const listing = useListingSlice(filtered, {
    query: search,
    searchText: (r) =>
      `${r.externalId} ${r.scenario} ${r.path} ${r.priorityLabel} ${r.lastStatus ?? ''}`,
    resetKey: `${resultFilter}:${priorityFilter}`,
  });
  const filtersActive = Boolean(
    search.trim() || resultFilter || priorityFilter,
  );

  const executeMutation = useMutation({
    mutationFn: async (testCaseIds?: string[]) => {
      const orgId = await getDefaultOrgId();
      return api<{ id: string }>(
        `/api/v1/orgs/${orgId}/projects/${projectId}/tcms/automation/scripts/execute`,
        {
          method: 'POST',
          body: JSON.stringify({
            testCaseIds,
            appUrl: envQuery.data?.appUrl ?? '',
          }),
        },
      );
    },
    onSuccess: (run) => {
      void onRun?.();
      void qc.invalidateQueries({
        queryKey: ['tcms-automation-scripts', projectId],
      });
      router.push(runHref(projectId, run.id));
    },
  });

  function needsExecutorForm() {
    return !envQuery.data?.appUrl;
  }

  function execute(ids?: string[]) {
    setError(null);
    if (needsExecutorForm()) {
      setExecutorIds(ids);
      setExecutorOpen(true);
      return;
    }
    executeMutation.mutate(ids);
  }

  const selectedCaseIds = scripts
    .filter((s) => selected.has(s.id))
    .map((s) => s.testCaseId);

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h3 className="text-base font-semibold text-fg">Automation</h3>
          <p className="mt-0.5 text-xs text-muted">
            Playwright scripts generated by AI Executor. Re-run selected or all.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <input
            className={listingSearchClass}
            placeholder="Search scripts"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <select
            className={listingFilterClass}
            value={resultFilter}
            onChange={(e) => setResultFilter(e.target.value)}
            aria-label="Filter by last result"
          >
            <option value="">All results</option>
            {RESULT_FILTERS.map((s) => (
              <option key={s} value={s}>
                {s.charAt(0) + s.slice(1).toLowerCase()}
              </option>
            ))}
          </select>
          <select
            className={listingFilterClass}
            value={priorityFilter}
            onChange={(e) => setPriorityFilter(e.target.value)}
            aria-label="Filter by priority"
          >
            <option value="">All priorities</option>
            {PRIORITY_FILTERS.map((s) => (
              <option key={s} value={s}>
                {s.charAt(0) + s.slice(1).toLowerCase()}
              </option>
            ))}
          </select>
          {canEdit ? (
            <>
              <Button
                type="button"
                size="sm"
                disabled={!selectedCaseIds.length || executeMutation.isPending}
                onClick={() => execute(selectedCaseIds)}
              >
                Execute selected
              </Button>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                disabled={!scripts.length || executeMutation.isPending}
                onClick={() => execute(undefined)}
              >
                Execute all
              </Button>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                onClick={() => {
                  void (async () => {
                    const orgId = await getDefaultOrgId();
                    await api(
                      `/api/v1/orgs/${orgId}/projects/${projectId}/tcms/automation/pause`,
                      { method: 'POST', body: '{}' },
                    );
                  })().catch((err) =>
                    setError(err instanceof Error ? err.message : 'Pause failed'),
                  );
                }}
              >
                Pause
              </Button>
              <Button
                type="button"
                size="sm"
                variant="danger"
                onClick={() => {
                  void (async () => {
                    const orgId = await getDefaultOrgId();
                    await api(
                      `/api/v1/orgs/${orgId}/projects/${projectId}/tcms/automation/stop`,
                      { method: 'POST', body: '{}' },
                    );
                  })().catch((err) =>
                    setError(err instanceof Error ? err.message : 'Stop failed'),
                  );
                }}
              >
                Stop
              </Button>
            </>
          ) : null}
        </div>
      </div>
      {error || executeMutation.error ? (
        <p className="text-sm text-danger">
          {error ||
            (executeMutation.error instanceof Error
              ? executeMutation.error.message
              : 'Execute failed')}
        </p>
      ) : null}

      <ListingTable
        rows={listing.pageRows}
        loading={scriptsQuery.isLoading}
        columnKey="automation-scripts"
        lockedColumnId="id"
        selectable={canEdit}
        selected={selected}
        onToggle={(id) => {
          setSelected((prev) => {
            const next = new Set(prev);
            if (next.has(id)) next.delete(id);
            else next.add(id);
            return next;
          });
        }}
        onToggleAll={(checked) => {
          setSelected(
            checked ? new Set(listing.pageRows.map((r) => r.id)) : new Set(),
          );
        }}
        empty={
          <ListingEmpty>
            {filtersActive
              ? 'No rows match these filters.'
              : 'No automated scripts yet. Run AI Executor on a cycle to generate them.'}
          </ListingEmpty>
        }
        columns={[
          {
            id: 'id',
            header: 'ID',
            className: 'font-medium',
            cell: (r) => r.externalId,
          },
          {
            id: 'title',
            header: 'Title',
            cell: (r) => r.scenario,
          },
          {
            id: 'priority',
            header: 'Priority',
            cell: (r) => r.priorityLabel,
          },
          {
            id: 'result',
            header: 'Last result',
            cell: (r) =>
              r.lastStatus ? (
                <Badge tone={resultTone(r.lastStatus)}>{r.lastStatus}</Badge>
              ) : (
                '—'
              ),
          },
          {
            id: 'path',
            header: 'Path',
            className: 'text-xs text-muted',
            cell: (r) => r.path,
          },
        ]}
        actions={
          canEdit
            ? (r) => [
                {
                  label: 'Execute',
                  onClick: () => execute([r.testCaseId]),
                },
              ]
            : undefined
        }
      />
      <ListingPager
        page={listing.page}
        totalPages={listing.totalPages}
        from={listing.from}
        to={listing.to}
        total={listing.total}
        pageSize={listing.pageSize}
        onPage={listing.setPage}
        onPageSize={listing.setPageSize}
      />
      <TcmsAiExecutorModal
        open={executorOpen}
        projectId={projectId}
        testCaseIds={executorIds}
        onClose={() => setExecutorOpen(false)}
        onStarted={(runId) => {
          void onRun?.();
          void qc.invalidateQueries({
            queryKey: ['tcms-automation-scripts', projectId],
          });
          router.push(runHref(projectId, runId));
        }}
      />
    </div>
  );
}
