import type { ReportManifest } from './types.js';

export function renderExecutiveMarkdown(manifest: ReportManifest): string {
  const scoreLines = (
    [
      ['Functional', manifest.scores.functional],
      ['Accessibility', manifest.scores.accessibility],
      ['Performance', manifest.scores.performance],
      ['Security', manifest.scores.security],
      ['UI/UX', manifest.scores.uiux],
    ] as const
  )
    .map(
      ([label, score]) =>
        `- **${label}:** ${score == null ? 'N/A' : Math.round(score)}`,
    )
    .join('\n');

  const findings =
    manifest.findings.length === 0
      ? '_No findings._'
      : manifest.findings
          .map(
            (f, i) =>
              `${i + 1}. **[${f.severity.toUpperCase()}] ${f.title}** (${f.category})\n   - ${f.description}${f.recommendation ? `\n   - Recommendation: ${f.recommendation}` : ''}`,
          )
          .join('\n');

  const recommendations =
    manifest.recommendations.length === 0
      ? '_None._'
      : manifest.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n');

  const testCases =
    manifest.testCases.length === 0
      ? '_No test cases._'
      : manifest.testCases
          .map((tc, i) => {
            const id = String(tc.id ?? tc.testId ?? `TC-${i + 1}`);
            const title = String(tc.title ?? tc.name ?? 'Untitled');
            const status = String(tc.status ?? tc.result ?? 'n/a');
            return `- \`${id}\` ${title} — ${status}`;
          })
          .join('\n');

  return `# QAForge Executive Report

**Project:** ${manifest.projectName}  
**App URL:** ${manifest.appUrl}  
**Execution ID:** ${manifest.executionId}  
**Status:** ${manifest.status}

## Scores

${scoreLines}

## Summary

| Passed | Failed | Total |
| ---: | ---: | ---: |
| ${manifest.summary.passed} | ${manifest.summary.failed} | ${manifest.summary.total} |

## Findings

${findings}

## Test Cases

${testCases}

## Recommendations

${recommendations}

---
_Generated by QAForge AI_
`;
}
